"""二手房标准字段与同义词映射（仅用于本项目 ingest/clean）。"""

from __future__ import annotations

STANDARD_COLUMNS: dict[str, str] = {
    "district": "城区",
    "community": "小区",
    "layout": "户型",
    "layout_normalized": "户型归一化",
    "area_m2": "建筑面积㎡",
    "total_price": "总价万元",
    "unit_price": "单价元每平米",
    "floor": "楼层",
    "floor_band": "楼层档低中高",
    "orientation": "朝向",
    "build_year": "建筑年代",
    "list_date": "挂牌日期",
    "decoration": "装修",
    "followers": "关注人数",
    "listing_title": "房源标题",
    "house_info_raw": "房屋信息原文",
    "follow_info_raw": "关注信息原文",
    "listing_id": "房源编号",
    "building_type": "建筑类型",
    "description_raw": "描述原文",
    "description_hint_subway": "描述推断地铁相关度0至1",
    "description_hint_school": "描述推断学区相关度0至1",
    "location_raw": "位置信息原文",
    "ingest_file": "上传源表文件名不含后缀",
    # 拆分过渡列（与 layout、area_m2 等价写入前可暂存，避免 LLM 臆造非标准键名报错）
    "area_m2_str": "面积拆分过渡",
    "area_m2_text": "面积拆分过渡2",
    "layout_str": "户型拆分过渡",
    "orientation_str": "朝向拆分过渡",
    "floor_text": "楼层原文",
    "publish_time_raw": "发布时间原文",
    "listing_time": "挂牌时间文本",
    "followers_str": "关注人数过渡",
    "decoration_str": "装修拆分过渡",
    "building_type_str": "建筑类型拆分过渡",
    # 规则化文本标签（由 description/location/title 等纯代码抽取，非查询时 LLM）
    "tag_near_subway": "标签近地铁",
    "tag_near_bus": "标签近公交",
    "tag_has_balcony": "标签带阳台",
    "tag_lighting": "标签采光相关",
    "tag_subway_station_hint": "标签地铁站名提示",
    "tag_elevator": "标签电梯",
}

STANDARD_COLUMN_KEYS: frozenset[str] = frozenset(STANDARD_COLUMNS.keys())

# 常见导出表头 -> 内部标准键
COLUMN_ALIASES: dict[str, str] = {
    "城区": "district",
    "区域": "district",
    "行政区": "district",
    "区县": "district",
    "小区": "community",
    "楼盘": "community",
    "小区名称": "community",
    "户型": "layout",
    "房型": "layout",
    "室厅": "layout",
    "建筑面积": "area_m2",
    "面积": "area_m2",
    "建面": "area_m2",
    "㎡": "area_m2",
    "平米": "area_m2",
    "总价": "total_price",
    "挂牌价": "total_price",
    "价格": "total_price",
    "万元": "total_price",
    "单价": "unit_price",
    "元/㎡": "unit_price",
    "元/m²": "unit_price",
    "楼层": "floor",
    "所在楼层": "floor",
    "楼层档": "floor_band",
    "低中高层": "floor_band",
    "朝向": "orientation",
    "建筑年代": "build_year",
    "建成年代": "build_year",
    "房龄": "build_year",
    "年代": "build_year",
    "挂牌日期": "list_date",
    "挂牌时间": "list_date",
    "挂牌时间文本": "listing_time",
    "装修": "decoration",
    "装修情况": "decoration",
    "装修类型": "decoration",
    "关注": "followers",
    "关注人数": "followers",
    "关注度": "followers",
    "房源标题": "listing_title",
    "标题": "listing_title",
    "房屋信息": "house_info_raw",
    "房源信息": "house_info_raw",
    "关注信息": "follow_info_raw",
    "房源编号": "listing_id",
    "编号": "listing_id",
    "建筑类型": "building_type",
    "房屋类型": "building_type",
    "物业类型": "building_type",
    "描述": "description_raw",
    "位置信息": "location_raw",
}


def normalize_header(name: str) -> str:
    s = str(name).strip().replace(" ", "")
    return COLUMN_ALIASES.get(s, s)
